name: Check appointments availability
on:
    schedule:
        - cron: "*/10 * * * *"
    workflow_dispatch:
jobs:
  scheduled:
    name: Checking appointments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run script
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_ADDRESS_TO: ${{ secrets.EMAIL_ADDRESS_TO }}
          EMAIL_ADDRESS_FROM: ${{ secrets.EMAIL_ADDRESS_FROM }}
        run: php -v
