name: Check appointments availability
on:
    schedule:
        - cron: "*/10 * * * *"
jobs:
  scheduled:
    name: Checking appointments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run script
        run: php run.php
